In [146]:
from sklearn.datasets import fetch_california_housing

# Load the California Housing dataset
housing = fetch_california_housing()

housing.data

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]])

In [147]:
housing.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [148]:
housing.target_names

['MedHouseVal']

In [149]:
import pandas as pd

In [150]:
d1=pd.DataFrame(data=housing.data,columns=housing.feature_names)
d1.head(5)

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [151]:
d2=pd.DataFrame(housing.target,columns=housing.target_names)
d2.head(1)

MedHouseVal
0        4.526

In [152]:
dataset=pd.concat((d1,d2)
          ,axis=1)
dataset.head(4)

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   

   Longitude  MedHouseVal  
0    -122.23        4.526  
1    -122.22        3.585  
2    -122.24        3.521  
3    -122.25        3.413

In [153]:
import numpy as np

In [154]:
dataset["Longitude"]=np.abs(dataset["Longitude"])
dataset.head(2)

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127    1.02381       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137    0.97188      2401.0  2.109842     37.86   

   Longitude  MedHouseVal  
0     122.23        4.526  
1     122.22        3.585

In [155]:
from sklearn.preprocessing import StandardScaler

In [156]:
ss=StandardScaler()

In [157]:
standard_scaler=ss.fit_transform(dataset)
standard_scaler

array([[ 2.34476576,  0.98214266,  0.62855945, ...,  1.05254828,
         1.32783522,  2.12963148],
       [ 2.33223796, -0.60701891,  0.32704136, ...,  1.04318455,
         1.32284391,  1.31415614],
       [ 1.7826994 ,  1.85618152,  1.15562047, ...,  1.03850269,
         1.33282653,  1.25869341],
       ...,
       [-1.14259331, -0.92485123, -0.09031802, ...,  1.77823747,
         0.8237132 , -0.99274649],
       [-1.05458292, -0.84539315, -0.04021111, ...,  1.77823747,
         0.87362627, -1.05860847],
       [-0.78012947, -1.00430931, -0.07044252, ...,  1.75014627,
         0.83369581, -1.01787803]])

In [158]:
dataset=pd.DataFrame(standard_scaler,columns=("MedInc","HouseAge","AveRooms","AveBedrms","Population","AveOccup","Latitude","Longitude","MedHouseVal"))

In [159]:
dataset.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  2.344766  0.982143  0.628559  -0.153758   -0.974429 -0.049597  1.052548   
1  2.332238 -0.607019  0.327041  -0.263336    0.861439 -0.092512  1.043185   
2  1.782699  1.856182  1.155620  -0.049016   -0.820777 -0.025843  1.038503   
3  0.932968  1.856182  0.156966  -0.049833   -0.766028 -0.050329  1.038503   
4 -0.012881  1.856182  0.344711  -0.032906   -0.759847 -0.085616  1.038503   

   Longitude  MedHouseVal  
0   1.327835     2.129631  
1   1.322844     1.314156  
2   1.332827     1.258693  
3   1.337818     1.165100  
4   1.337818     1.172900

In [160]:
dataset=np.abs(dataset)

In [161]:
x=dataset.iloc[:,:8]
x.head(2)

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  2.344766  0.982143  0.628559   0.153758    0.974429  0.049597  1.052548   
1  2.332238  0.607019  0.327041   0.263336    0.861439  0.092512  1.043185   

   Longitude  
0   1.327835  
1   1.322844

In [162]:
y=dataset.iloc[:,-1]
y.head(2)

0    2.129631
1    1.314156
Name: MedHouseVal, dtype: float64

In [163]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=45)
len(x_train),len(x_test)

(16512, 4128)

<h5>Support vector Regressor</h5>

In [164]:
from sklearn.svm import SVR

In [165]:
sv=SVR(kernel='rbf')

In [166]:
sv.fit(x_train,y_train)

SVR()

In [167]:
y_pred=sv.predict(x_test)
y_pred

array([1.29925206, 0.38211639, 0.32506433, ..., 0.35910456, 0.94632   ,
       0.61388055])

In [168]:
sv.score(x_test,y_pred)

1.0