<h3>Simple Train test split<h3>

In [18]:
from sklearn.datasets import fetch_california_housing

# Load the California Housing dataset
housing = fetch_california_housing()

housing.data

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]])

In [19]:
housing.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [20]:
housing.target_names

['MedHouseVal']

In [21]:
import pandas as pd 
import numpy as np 
df = pd.DataFrame(housing.data, columns=housing.feature_names)
df['Target'] = housing.target  # Add target column to DataFrame
df.head()


MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  Target  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521  
3    -122.25   3.413  
4    -122.25   3.422

In [22]:
df.shape

(20640, 9)

In [23]:
x=pd.DataFrame(housing.data, columns=housing.feature_names)

x

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [24]:
y= housing.target
y

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=35)  
  #every time changing the value of random_state with cahnging the value ofx_train and cahnging the accuracy scoreof data 


In [26]:
from sklearn.preprocessing import StandardScaler

In [27]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(x_train)
X_test_scaled = scaler.transform(x_test)

In [28]:
from sklearn.tree import DecisionTreeRegressor

In [29]:
dtr=DecisionTreeRegressor(splitter='best')

In [30]:
dtr.fit(X_train_scaled ,y_train)

DecisionTreeRegressor()

In [31]:
y_pred=dtr.predict(X_test_scaled)

In [32]:
from sklearn.metrics import r2_score

In [33]:
r1=r2_score(y_test,y_pred)
r1

0.6326348145725539

**usingcross validation**

In [47]:
from sklearn.model_selection import cross_val_score
score_of_DecsionTree_regression=cross_val_score(DecisionTreeRegressor(),x,y,cv=3)
score_of_DecsionTree_regression

array([0.24590306, 0.4783979 , 0.25545073])

In [48]:
np.average(score_of_DecsionTree_regression)

0.3265838983422771

**Linear Regression**

In [38]:
from sklearn.linear_model import LinearRegression

In [39]:
l=LinearRegression()


In [40]:
l.fit(x_train,y_train)

LinearRegression()

In [41]:
y_predict=l.predict(x_test)


In [42]:
r2_score(y_test,y_pred)

0.6326348145725539

**using cross validation**

In [44]:
score_of_linearRegression=cross_val_score(LinearRegression(),x,y,cv=10)

In [45]:
score_of_linearRegression

array([0.48254494, 0.61416063, 0.42274892, 0.48178521, 0.55705986,
       0.5412919 , 0.47496038, 0.45844938, 0.48177943, 0.59528796])

In [46]:
score_of_linearRegression.mean()

0.5110068610524556